"""add sender_id to messages

Revision ID: 48523a34121a
Revises: 4e1a3a35a089
Create Date: 2025-04-25 15:04:59.873217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48523a34121a'
down_revision: Union[str, None] = '4e1a3a35a089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['user_id'], ondelete='CASCADE')

    messages_table = sa.table(
        'message',
        sa.column('message_id', sa.Integer),
        sa.column('thread_id', sa.Integer),
        sa.column('sender_id', sa.Integer),
        sa.column('hasActiveMessage', sa.Boolean),
        sa.column('text', sa.Text),
        sa.column('timeStamp', sa.DateTime)
    )

    op.bulk_insert(
        messages_table,
        [
            {
                "message_id": 1,
                "thread_id": 1,
                "sender_id": 2,
                "hasActiveMessage": False,
                "text": "Hi John, I have a question about my upcoming appointment.",
                "timeStamp": "2025-02-16T10:00:00"
            },
            {
                "message_id": 2,
                "thread_id": 1,
                "sender_id": 1,
                "hasActiveMessage": True,
                "text": "Hi Jane, sure. What can I help you with?",
                "timeStamp": "2025-02-16T10:05:00"
            },
            {
                "message_id": 3,
                "thread_id": 2,
                "sender_id": 4,
                "hasActiveMessage": False,
                "text": "Hello Mike, I need to reschedule my appointment.",
                "timeStamp": "2025-02-16T11:00:00"
            },
            {
                "message_id": 4,
                "thread_id": 2,
                "sender_id": 3,
                "hasActiveMessage": True,
                "text": "Hi Sarah, that's fine. Let me know your preferred time.",
                "timeStamp": "2025-02-16T11:10:00"
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'sender_id')
    # ### end Alembic commands ###
