"""Add is_booked to time_slot

Revision ID: 9870ac6d4cf2
Revises: b01fc8702548
Create Date: 2025-04-06 22:44:51.632949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9870ac6d4cf2'
down_revision: Union[str, None] = 'b01fc8702548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=75),
               existing_nullable=False)
    op.add_column('time_slots', sa.Column('is_booked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_slots', 'is_booked')
    op.alter_column('service', 'description',
               existing_type=sa.String(length=75),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
